### ISSUE TITLE
 change for each-method in ResultListenerProxy to be deterministic

### ISSUE THREAD

**Issue by beta2k** [YABench/yabench#23]
if we go for the discussed workaround for the oracle (comparing the results of the oracle with the engine results without the need to compare correct borders (similar than a line-by-line comparison between two files)), we need to change the for-each-method in the ResultListenerProxy to be deterministic, i.e., results appear in the order they were streamed.

**Comment by KMax** [comment]
I just tried to replace `forEach` by `forEachOrdered` by it doesn't help much, because the result ordered from older to younger which doesn't help :( So I suggest to consider the content as an unordered list.
