### ISSUE TITLE
The engine should wait while all input triples are outside windows

### ISSUE THREAD

**Issue by KMax** [YABench/yabench#5]
As we know, now the engine stops working once the last input triple send to it, because of that we lose some query results.

yabench-csparql:
* parse the window size from the given query
* sleep during the window size after the last input triple send to the engine

yabench-oracle:
* compute new windows while there are triples for them

**Comment by beta2k** [comment]
this is done for now. however, this issue only applies, if we deal with C-SPARQL window semantics. if we have CQELS then we would not need to wait until the final window closes, because results are returned immediately and we won't "forget" any results/triples.

**Comment by beta2k** [comment]
as discussed we can close this issue, because if we will have CQELS we will create another program and reuse code of C-SPARQL (which may then be moved to our commons-project) and then can implement it differently, i.e., without this waiting at the end.
