### ISSUE TITLE
Run preliminary tests with C-SPARQL to verify the framework

### ISSUE THREAD

**Issue by KMax** [YABench/yabench#7]
Things to look at:
* memory consumption of each component
* reporting with big number of windows
* what else?

**Comment by beta2k** [comment]
- big number of triples per window or short windows or both
- complex queries (many graph patterns)

**Comment by KMax** [comment]
Test 1 (Q1):
* duration: 1h
* stations: 200
* interval: 1m
* temp: 0 - 100
* window:
    * size: 5m
    * slide: 2m
